name: Promote Staged Milestone

on:
  workflow_dispatch:
    inputs:
      buildName:
        description: 'The Artifactory Build Name'
        required: true
      buildNumber:
        description: 'The Artifactory Build'
        required: true

jobs:
  staging:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'spring-projects'
    steps:

      - uses: jfrog/setup-jfrog-cli@v3
        with:
          version: 2.50.2
        env:
          JF_ENV_SPRING: ${{ secrets.JF_ARTIFACTORY_SPRING }}

      - name: Promote Build
        run: |
          jfrog rt build-promote ${{ inputs.buildName }} ${{ inputs.buildNumber }} libs-milestone-local