name: Promote Staged Milestone

on:
  workflow_dispatch:
    inputs:
      buildName:
        description: 'The Artifactory Build Name'
        required: true
        type: string
      buildNumber:
        description: 'The Artifactory Build'
        required: true
        type: number

jobs:
  promote_milestone:
    uses: ./.github/workflows/spring-artifactory-promote-milestone.yml
    with:
      buildName: ${{ inputs.buildName }}
      buildNumber: ${{ inputs.buildNumber }}
    secrets: inherit