name: Perform Release with Artifactory

on:
  workflow_call:
    inputs:
      buildToolArgs:
        description: 'Additional Maven or Gradle command arguments: tasks, goals, plugins etc. The `install` for Maven is included. The `build` and `artifactoryPublish` for Gradle are included.'
        required: false
        type: string

env:
  GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_REPO_TOKEN }}

jobs:
  releaseVersion:
    runs-on: ubuntu-latest
    outputs:
      releaseVersion: ${{ steps.release-version.outputs.releaseVersion }}

    steps:

      - uses: actions/checkout@v4
        with:
          show-progress: false

      - name: Find Current Version to Release
        id: release-version
        run: |
          if test -f pom.xml
          then
            CURRENT_VERSION=$(./mvnw help:evaluate -Dexpression="project.version" -q -DforceStdout)
          else
            CURRENT_VERSION=$(./gradlew properties --no-daemon --console=plain -q | grep "^version:" | awk '{printf $2}')
          fi
          export CANDIDATE_VERSION=${CURRENT_VERSION/-SNAPSHOT}
          RELEASE_VERSION=$(gh api repos/$GITHUB_REPOSITORY/milestones --jq 'map(select(.title | startswith(env.CANDIDATE_VERSION))) | .[0] | .title')
          if [ -z $RELEASE_VERSION ]; then
            echo "::error::No scheduled milestone for $CURRENT_VERSION version."
            exit 1
          fi
          echo releaseVersion=$RELEASE_VERSION >> $GITHUB_OUTPUT
          echo "::notice::RELEASE VERSION=$RELEASE_VERSION"

  staging:
    needs: releaseVersion
    uses: spring-projects/spring-integration-aws/.github/workflows/spring-stage-release.yml@main
    with:
      releaseVersion: ${{ needs.releaseVersion.outputs.releaseVersion }}
      buildToolArgs: ${{ inputs.buildToolArgs }}
    secrets: inherit

  verify-staged:
    needs: [releaseVersion, staging]
    uses: ./.github/workflows/verify-staged-artifacts.yml
    with:
      releaseVersion: ${{ needs.releaseVersion.outputs.releaseVersion }}
    secrets: inherit

  promote-milestone:
    needs: [staging, verify-staged]
    if: ${{ (contains(inputs.releaseVersion, '-M') || contains(inputs.releaseVersion, '-RC')) }}
    uses: spring-projects/spring-integration-aws/.github/workflows/spring-artifactory-promote-milestone.yml@main
    with:
      buildName: ${{ needs.staging.outputs.buildName }}
      buildNumber: ${{ needs.staging.outputs.buildNumber }}
    secrets: inherit

  promote-ga:
    needs: [staging, verify-staged]
    if: ${{ !contains(inputs.releaseVersion, '-') }}
    uses: spring-projects/spring-integration-aws/.github/workflows/spring-artifactory-promote-central.yml@main
    with:
      buildName: ${{ needs.staging.outputs.buildName }}
      buildNumber: ${{ needs.staging.outputs.buildNumber }}
    secrets: inherit

  finalize:
    if: ${{ !(failure() || cancelled()) }}
    needs: [releaseVersion, promote-milestone, promote-ga]
    uses: spring-projects/spring-integration-aws/.github/workflows/spring-finalize-release.yml@main
    with:
      milestone: ${{ needs.releaseVersion.outputs.releaseVersion }}
    secrets: inherit