name: CI Artifactory SNAPSHOT Build for Gradle

on:
  workflow_call:
    inputs:
      gradleTasks:
        description: 'Additional Gradle tasks. The `build` and `artifactoryPublish` are included.'
        required: false
        default: 'dist'
        type: string

env:
  GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GRADLE_ENTERPRISE_CACHE_USER }}
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GRADLE_ENTERPRISE_CACHE_PASSWORD }}
  GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_SECRET_ACCESS_KEY }}

jobs:
  build_snapshot:
    runs-on: ubuntu-latest
    name: CI Build SNAPSHOT for ${{ github.ref_name }}
    steps:

      - uses: actions/checkout@v3

      - name: Set up Gradle
        uses: spring-io/spring-gradle-build-action@v2

      - name: Checkout Common Repo
        uses: actions/checkout@v3
        with:
          repository: spring-projects/spring-integration-aws
          path: init

      - name: Copy the artifactory-init.gradle
        run: rsync init/.github/artifactory-init.gradle ~/.gradle/init.d/

      - uses: jfrog/setup-jfrog-cli@v3
        with:
          version: 2.50.4
        env:
          JF_ENV_SPRING: ${{ secrets.JF_ARTIFACTORY_SPRING }}

      - name: Configure JFrog Cli
        run: |
          jf gradlec \
            --use-wrapper \
            --repo-deploy libs-snapshot-local
          echo JFROG_CLI_BUILD_NAME=${{ github.event.repository.name }}-${{ github.ref_name }} >> $GITHUB_ENV
          echo JFROG_CLI_BUILD_NUMBER=$GITHUB_RUN_NUMBER >> $GITHUB_ENV

      - name: Build and Publish
        run: |
          jf gradle build ${{ inputs.gradleTasks }} artifactoryPublish
          jf rt build-publish

