name: Verify Staged Artifacts

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release version like 3.0.0-M1, 3.1.0-RC1, 3.2.0 etc.'
        required: true
        type: string

jobs:
  verify-staged-with-jfrog:
    runs-on: ubuntu-latest
    steps:

      - uses: jfrog/setup-jfrog-cli@v3
        with:
          version: 2.51.1
        env:
          JF_ENV_SPRING: ${{ secrets.JF_ARTIFACTORY_SPRING }}

      - name: Download Artifact from Staging Repo
        run: |
          jfrog rt download libs-staging-local/org/springframework/integration/spring-integration-aws/${{ inputs.releaseVersion }}/spring-integration-aws-${{ inputs.releaseVersion }}.jar spring-integration-aws.jar
          if [ ! -f spring-integration-aws.jar ]
          then
            echo "::error title=No staged artifact::No spring-integration-aws-${{ inputs.releaseVersion }}.jar in staging repository"
            exit 1
          fi